# Project options - can change the overall project title
# and the name of the output directory here
# Uncomment the post-render command to use the 
# return-to-source post script - see Readme
project:
  title: "Docs"
  output-dir: "_output"

# options for all formats - suggested not to change
from: markdown+raw_attribute+raw_tex
standalone: true
self-contained: true
slide-level: 2